name: Deploy to Render
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Render CLI
        run: |
          curl -L https://github.com/renderinc/cli/releases/download/v0.26.0/render_linux_x86_64.tar.gz | tar xz
          sudo mv render /usr/local/bin
          
      - name: Deploy to Render
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render deploy --service-id $RENDER_SERVICE_ID --api-key $RENDER_API_KEY
